# Generated by Django 5.2.6 on 2025-10-07 14:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_status'),
        ('lessons', '0002_lessoncompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_start_date', models.DateField()),
                ('class_start_time', models.TimeField()),
                ('class_end_date', models.DateField()),
                ('class_end_time', models.TimeField()),
                ('frequency', models.PositiveSmallIntegerField(default=1)),
                ('duration_weeks', models.PositiveSmallIntegerField(default=2)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('capacity', models.PositiveSmallIntegerField(default=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('occupied', 'Occupied'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='courses.course')),
                ('lessons', models.ManyToManyField(blank=True, related_name='classrooms', to='lessons.lesson')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn'), ('waitlisted', 'Waitlisted')], default='enrolled', max_length=12)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classrooms.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped')], default='active', max_length=12)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classrooms.classroom')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__lte', 20)), name='capacity_max_20'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'classroom')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonenrollment',
            unique_together={('student', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('student', 'lesson')},
        ),
    ]
